"""added tickets types

Revision ID: 79ddd95fa814
Revises: e7022ecf125c
Create Date: 2026-06-09 15:00:47.999514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79ddd95fa814'
down_revision = 'e7022ecf125c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('serial_number', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('serial_number')
        batch_op.drop_column('ticket_type')

    # ### end Alembic commands ###
